# --- Defaults ---

# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc2" # Environment name
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 20 # Number of episodes to test for
test_interval: 2000 # Test after {} timesteps have passed
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 2000 # Log summary of stats after every {} timesteps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 2000 # Log training stats every {} timesteps
t_max: 10000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: False # Log results to tensorboard
save_model: True # Save the models to disk
save_model_interval: 2000000 # Save models after this many timesteps
checkpoint_path: '' #'results/models/multi_head_qmix__2021-12-04_08-29-14/' #'results/models/qmix__2022-03-09_09-06-55/' #'results/models/graph_qmix__2021-12-04_08-13-05/' #'results/models/graph_qmix__2021-12-04_08-14-11/' # './results/models/qmix__2021-05-20_11-28-12/' #'./results/models/qmix__2022-03-09_09-06-41/' # # './results/models/multi_head_qmix__2021-12-04_22-41-44/' #'results/models/qmix__2021-05-20_11-28-12/' #'./results/models/multi_head_qmix__2021-12-04_08-25-37/' #'results/models/graph_qmix__2021-12-23_09-15-04/' #'./results/models/multi_head_qmix__2021-12-23_09-15-48/' #'./results/models/qmix__2021-06-03_14-00-13/' # './results/models/multi_head_qmix__2021-12-23_09-15-48/' # './results/models/graph_qmix__2021-12-22_13-47-48/' # './results/models/multi_head_qmix__2021-12-22_13-49-59/' # './results/models/graph_qmix__2021-12-22_13-47-48/' # './results/models/multi_head_qmix__2021-12-22_13-49-59/' #'./results/models/graph_qmix__2021-12-22_13-47-48/' # './results/models/graph_qmix__2021-04-30_19-58-11/' #'./results/models/graph_qmix__2021-12-04_08-13-05/' #"./results/models/multi_head_qmix__2021-11-16_16-01-28/" # Load a checkpoint from this path      ./results/models/graph_qmix__2021-04-30_09-19-36/
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)     !!!!!
load_step: 0 #2000042 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: True # Saving the replay of the model loaded from checkpoint_path        !!!!!
local_results_path: "results" # Path for local results
continous_mode: True

#'./results/models/multi_head_qmix__2021-12-04_08-29-14/'# 
# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"
